### ISSUE TITLE
Error When run the App on IOS Device

### ISSUE THREAD

**Issue by Hasankanso** [channdara/flutter_translator#3]
Error code :

```
[VERBOSE-2:ui_dart_state.cc(209)] Unhandled Exception: Null check operator used on a null value
#0      BasicMessageChannel.binaryMessenger (package:flutter/src/services/platform_channel.dart:52:86)
#1      BasicMessageChannel.send (package:flutter/src/services/platform_channel.dart:60:38)
#2      UserDefaultsApi.getAll (package:shared_preferences_ios/messages.g.dart:134:23)
#3      SharedPreferencesIOS.getAll (package:shared_preferences_ios/shared_preferences_ios.dart:45:53)
#4      SharedPreferences._getSharedPreferencesMap (package:shared_preferences/shared_preferences.dart:164:57)
#5      SharedPreferences.getInstance (package:shared_preferences/shared_preferences.dart:33:19)
#6      TranslatorUtil._getLocale (package:flutter_translator/src/util.dart:13:42)
#7      TranslatorUtil.getInitLocale (package:flutter_translator/src/util.dart:33:18)
#8      TranslatorGenerator._handleLocale (package:flutter_translator/src/generator.dart:71:43)
#9      TranslatorGenerator.init (package:flutter_translator/<…>
```
reproduce:
1. open IOS simulator
2. integrate flutter_translate as described in the documentation
3. run the app on the iOS device using Android Studio Run button

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.8.1, on macOS 12.0.1 21A559 darwin-arm, locale de-DE)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 13.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2020.3)
[✓] VS Code (version 1.62.2)
[✓] VS Code (version 1.63.2)
[✓] Connected device (2 available)

• No issues found!
```

**Comment by channdara** [comment]
@Hasankanso 
Thank you for your report. I will check and fix this issue soon.
